[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  'solmate/src/=lib/solmate/',
  "@chainlink/=lib/chainlink/",
]
